---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'master'
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        exclude: test_data/.*\.py$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/miki725/importanize
    rev: 'master'
    hooks:
      - id: importanize
        language_version: python3

  - repo: https://github.com/python/black
    rev: 'master'
    hooks:
      - id: black
        args: [--line-length=80, --safe]
        language_version: python3

  - repo: https://github.com/mgedmin/check-manifest
    rev: 'master'
    hooks:
      - id: check-manifest

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.3
      hooks:
      -   id: flake8
