# Config file for automatic testing at travis-ci.org

dist: xenial
sudo: false
branches:
  only:
    - master

language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.7"
  - "3.6"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox-travis
  - pip install "cryptography < 3"
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: tox

after_success: coveralls
